chore:
- .gitattributes
- .github/**/*
- .gitignore
- .mvn/**/*
- .pre-commit-config.yaml
- .sonarcloud.properties
- .vscode/**/*
- Jenkinsfile

dependencies:
- pom.xml

documentation:
- CONTRIBUTING.md
- README.md
- LICENSE.txt

test:
- src/**/*.sh
- src/**/Dockerfile
- src/**/lsb_release-a
- src/**/os-release
