chore:
  - changed-files:
    - any-glob-to-any-file:
      - .gitattributes
      - .github/**/*
      - .gitignore
      - .mvn/**/*
      - .pre-commit-config.yaml
      - .sonarcloud.properties
      - .vscode/**/*
      - Jenkinsfile

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - CONTRIBUTING.md
      - README.md
      - LICENSE.txt
      - src/main/**/*.html

tests:
  - changed-files:
    - any-glob-to-any-file:
      - src/**/*.sh
      - src/**/Dockerfile
      - src/**/lsb_release-a
      - src/**/os-release
