# Using an updated Gitpod docker image (when using a non default JDK or tools)
image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn install -DskipTests=false
  - name: Update settings.xml
    before: |
      cp .mvn/gitpod-mvn-settings.xml ~/.m2/settings.xml
      cd $GITPOD_REPO_ROOT


vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - github.vscode-pull-request-github
    # - redhat.vscode-xml
    # - hbenl.test-adapter-converter
    # - hbenl.vscode-test-explorer

    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
